language: node_js
node_js:
    - "node"
sudo: required
env:
  - TEST_DIR=Dashboard
  - TEST_DIR=WebServer
script: cd $TEST_DIR && npm install --dev && npm test
before_install:
#    - export DISPLAY=:99.0
#    - sh -e /etc/init.d/xvfb start
#before_script:
#    - npm install --dev