language: node_js
node_js:
    - "node"
sudo: required
#script: node_modules/karma/bin/karma start --single-run
script: 0
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
#    - npm install